version: "3"

services:
  bot:
    container_name: bidlik
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
      - bidlik-net

  db:
    container_name: postgres
    image: postgres:10-alpine
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  bidlik-net:
    name: bidlik-net
